server:
  port: 8762

spring:
  application:
    name: user
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

