server:
  port: 8700

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
  redis:
    host: localhost
    port: 6379
    #password: ${REDIS_PASSWORD:}
    lettuce:
      pool:
        max-active: 300
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&allowMultiQueries=true&tinyInt1isBit=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
