server:
  port: 8700

spring:
  application:
    name: gateway
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
    gateway:
      routes:
        #用户模块
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
  redis:
    host: localhost
    port: 6379
    #password: ${REDIS_PASSWORD:}
    lettuce:
      pool:
        max-active: 300
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms

